version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - "blog_staticfiles:/usr/share/nginx/blog_staticfiles"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "80:80"
    depends_on:
      - blog_app

  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "${PG_NAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_USER: "${PG_USERNAME}"

  blog_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: /usr/bin/env python /app/entrypoint.py
    volumes:
      - "blog_app:/app"
      - "blog_staticfiles:/app/staticfiles"
    env_file:
      - .env
    depends_on:
      - redis
      - celery_worker
      - db

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A BlogApp worker -l INFO --pool=solo
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - "redis:/data"

volumes:
  db:
  redis:
  blog_app:
  blog_staticfiles:
