name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: created .env file
        run: |
          touch .env
          echo PG_NAME=${{ secrets.PG_NAME }}  >> .env
          echo PG_PASSWORD=${{ secrets.PG_PASSWORD }} >> .env
          echo PG_USERNAME=${{ secrets.PG_USERNAME }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }} >> .env
          echo CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }} >> .env
          echo REDIS_ADDRESS=${{ secrets.REDIS_ADDRESS }} >> .env
          cat .env


      - name: start services
        run: docker-compose up -d

      - name: Code Formatting with Black
        run: docker-compose run blog_app black .

      - name: Run Tests and Generate Coverage Report
        run: docker-compose run blog_app sh -c "coverage run manage.py test && coverage report"


      - name: Shut down
        run: docker-compose down